name: Deploy on Cloud Run

on:
    push:
        branches:
            - development
jobs:
    build_and_upload_container:
        name: Build and Upload Container
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        # - name: Set up Google Cloud SDK
        #   uses: google-github-actions/setup-gcloud@master
        #   with:
        #     project_id: ${{ secrets.GCP_PROJECT_ID }}
        #     service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        #     service_account_key: ${{ secrets.GCP_SA_KEY }}
        # - name: Configure Docker
        #   uses: docker/setup-buildx-action@v1
        # - name: Build and push container
        #   uses: docker/build-push-action@v2
        #   with:
        #     context: .
        #     push: true
        #     tags: gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-image-name:latest
