name: Deploy on Cloud Run

on:
    push:
        branches:
            - development
jobs:
    build_and_upload_container:
        name: Build and Upload Container
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - id: 'auth'
          name: 'Authenticate with Google Cloud'
          uses: google-github-actions/auth@v1
          with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'
            token_format: 'access_token'

        - run: |-
            echo '${{ steps.auth.outputs.access_token }}'

