name: Deploy on cloud Run

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: HELLO_MESSAGE
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v1'
      env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT }}
        ARTIFACT_REGION: ${{ secrets.ARTIFACT_REGION }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
      with:
        service: 'gitter'
        image: $ARTIFACT_REGION-docker.pkg.dev/$GOOGLE_PROJECT/$REPO_NAME/gitter:latest
        project_id: $GOOGLE_PROJECT
        region: $ARTIFACT_REGION
        env_vars:
          "HELLO_MESSAGE=${{ secrets.HELLO_MESSAGE }}"
        flags: '--allow-unauthenticated'

    - name: 'Use output'
      run: 'Deployed URL "${{ steps.deploy.outputs.url }}"'


