name: Deploy on cloud Run

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: HELLO_MESSAGE
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: 'Deploy Image'
      run: |
        gcloud run deploy gitter \
          --image ${{ secrets.ARTIFACT_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/${{ secrets.REPO_NAME }}/${{ secrets.CONTAINER_NAME }} \
          --region us-central1 \
          --set-env-vars 'HELLO_MESSAGE=I'"'"'m from GitHub' \
          --platform managed \
          --allow-unauthenticated \
          --quiet \
          --verbosity debug


